### ISSUE TITLE
Add documentation draft

### ISSUE THREAD

**Issue by edvinnn** [optmzr/d7024e-dht#2]
The **required content** of the lab report is described in the **Workflow** section in the lab assignment text. For example:

- draft architecture description
- initial backlog, prioritized with objective to first reach a minimal working solution
- solution outlines for your prioritized items on the backlog and objectives in the lab assignment

The report shall be **uploaded at midnight 2 days before** your review slot (so reviewers will have one day to check it). Book your time slot with a supervisor for review. The link for booking a time slot is here:

**Comment by edvinnn** [comment]
Snyggt strukturerat med skelettet @optmzr. Jag lade till beskrivning på CLI-delen under sprint 0 👍

**Comment by optmzr** [comment]
Gött! Då är det bara @Hjortsberg kvar då :)
-- 
MVH/Regards, William Wennerström.
Phone: +46 (0) 707 21 82 10
