### ISSUE TITLE
Design bucket data structure (routing table)

### ISSUE THREAD

**Issue by optmzr** [optmzr/d7024e-dht#22]

**Comment by optmzr** [comment]
Here`s my proposal:

```go
package bucket

const idLength = 160
const bucketSize = 20

type Buckets [idLength]Bucket
type Bucket [bucketSize]Contact

type Contact struct {
    NodeID []byte,
    Address net.UDPAddr,
    Port uint,
}

func (b Buckets) Add(c Contact) error {}
func (b Buckets) Closest(id []byte) (error, Contact) {}
func (b Buckets) remove(id []byte) {}
```

I kept the `remove` as private as I'm not sure if it will be used by any outside package but the bucket package.

The `Buckets` type could also hold a internal slice that is initialized with a specific length instead of using a constant.

**Comment by optmzr** [comment]
@edvinnn @Hjortsberg does this look good?

**Comment by Hjortsberg** [comment]
@optmzr, is closest an alias for the XOR- functionality?

**Comment by optmzr** [comment]
The idea is that Closest will internally run the XOR distance and return the closest node. So yes, but you don't get any distance, instead you'll get the node. 
-- 
MVH/Regards, William Wennerström.
Phone: +46 (0) 707 21 82 10

**Comment by Hjortsberg** [comment]
I GUESS THAT SOUNDS GOOD!
