### ISSUE TITLE
Design object data structure (storage)

### ISSUE THREAD

**Issue by optmzr** [optmzr/d7024e-dht#23]
Probably just a simple hash table?

**Comment by Hjortsberg** [comment]
Design strategy is now to spawn one or two go routines that checks the dates of all the stored items **tExpire** and **tRepublish**. Set the sleep of the Go routine to the time of of the closest date.

**Comment by optmzr** [comment]
of of of of of of of of of of of of of of of of of of of of of of of of of of of

**Comment by Hjortsberg** [comment]
Design strategy is now to spawn one or two go routines that checks the dates of all the stored items **tExpire** and **tRepublish**. Set the sleep of the Go routine to the time of of the closest date.

**Comment by optmzr** [comment]
Implementation has begun in #25
